"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Plus, Save, Trash2, RotateCcw } from "lucide-react";
import { DEFAULT_LOGISTICS_CONFIG, MOUNT_LABELS, sanitizeConfig } from "@/lib/settings";
import type { AdditionalItem, LogisticsConfig, MountType } from "@/lib/types";

const KEY="famossul-logistics-config-v1";
const mounts:MountType[]=["MONTADO_HS","MONTADO_TIMADEL","COMPLEMENTO_OBRA","REVENDA","MONTADO_ESTANCIA"];

export default function SettingsClient(){
 const [cfg,setCfg]=useState<LogisticsConfig>(DEFAULT_LOGISTICS_CONFIG); const [saved,setSaved]=useState(false);
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);if(raw)setCfg(sanitizeConfig(JSON.parse(raw)));}catch{}},[]);
 function setRule(m:MountType,key:string,value:string){setCfg(c=>{const copy=structuredClone(c) as any;copy[m][key]=Number(value)||0;return copy});setSaved(false)}
 function save(){localStorage.setItem(KEY,JSON.stringify(cfg));setSaved(true);setTimeout(()=>setSaved(false),1800)}
 function reset(){setCfg(structuredClone(DEFAULT_LOGISTICS_CONFIG));localStorage.removeItem(KEY);setSaved(false)}
 function addItem(){const item:AdditionalItem={id:crypto.randomUUID(),label:"Novo item",text:"",target:"AMBOS",position:"OBSERVACAO",enabled:true};setCfg(c=>({...c,additionalItems:[...c.additionalItems,item]}))}
 function editItem(id:string,key:keyof AdditionalItem,value:any){setCfg(c=>({...c,additionalItems:c.additionalItems.map(i=>i.id===id?{...i,[key]:value}:i)}))}
 function removeItem(id:string){setCfg(c=>({...c,additionalItems:c.additionalItems.filter(i=>i.id!==id)}))}
 return <div className="shell"><header className="topbar"><div className="brand"><span className="leaf"/><div>famossul<small>Configurações operacionais</small></div></div><Link className="btn ghost" href="/dashboard"><ArrowLeft size={16}/> Voltar</Link></header><main className="main"><div className="eyebrow">Administração</div><h1 className="title">Configurações</h1><p className="subtitle">Ajuste limites logísticos e textos adicionais sem alterar o código. Estas configurações ficam salvas neste navegador e são enviadas junto com cada processamento.</p>
 <div className="settingsGrid">{mounts.map(m=><section className="card settingsCard" key={m}><h3>{MOUNT_LABELS[m]}</h3><div className="formGrid"><label>Máx. portas<input type="number" value={cfg[m].maxDoors} onChange={e=>setRule(m,"maxDoors",e.target.value)}/></label><label>Máx. m³<input type="number" step="0.001" value={cfg[m].maxM3} onChange={e=>setRule(m,"maxM3",e.target.value)}/></label><label>Máx. jogos alizar<input type="number" value={cfg[m].maxTrimGames} onChange={e=>setRule(m,"maxTrimGames",e.target.value)}/></label><label>Máx. jogos marco<input type="number" value={cfg[m].maxFrameGames} onChange={e=>setRule(m,"maxFrameGames",e.target.value)}/></label>{m==="REVENDA"&&<><label>Portas papelão<input type="number" value={cfg.REVENDA.maxDoorsCardboard} onChange={e=>setRule(m,"maxDoorsCardboard",e.target.value)}/></label><label>Portas esp. 41<input type="number" value={cfg.REVENDA.maxDoorsThickness41} onChange={e=>setRule(m,"maxDoorsThickness41",e.target.value)}/></label></>}</div></section>)}</div>
 <section className="card settingsCard" style={{marginTop:18}}><h3>Pedido misto</h3><div className="formGrid"><label>Máximo m³ por pallet<input type="number" step="0.001" value={cfg.mixedMaxM3} onChange={e=>setCfg(c=>({...c,mixedMaxM3:Number(e.target.value)||0}))}/></label><label>Observação padrão no romaneio<input value={cfg.romaneioNote||""} onChange={e=>setCfg(c=>({...c,romaneioNote:e.target.value}))}/></label><label>Observação padrão na etiqueta<input value={cfg.labelNote||""} onChange={e=>setCfg(c=>({...c,labelNote:e.target.value}))}/></label></div></section>
 <section className="card settingsCard" style={{marginTop:18}}><div className="pkghead" style={{padding:0,border:0,background:"transparent"}}><div><h3 style={{marginBottom:4}}>Itens adicionais</h3><p className="subtitle" style={{margin:0}}>Textos opcionais que podem aparecer no romaneio, etiqueta ou ambos.</p></div><button className="btn secondary" onClick={addItem}><Plus size={15}/> Adicionar</button></div>{!cfg.additionalItems.length?<div className="empty">Nenhum item adicional cadastrado.</div>:<div className="tablewrap" style={{marginTop:14}}><table className="table"><thead><tr><th>Ativo</th><th>Nome</th><th>Texto</th><th>Destino</th><th>Posição</th><th></th></tr></thead><tbody>{cfg.additionalItems.map(i=><tr key={i.id}><td><input type="checkbox" checked={i.enabled} onChange={e=>editItem(i.id,"enabled",e.target.checked)}/></td><td><input value={i.label} onChange={e=>editItem(i.id,"label",e.target.value)}/></td><td><input value={i.text} onChange={e=>editItem(i.id,"text",e.target.value)}/></td><td><select value={i.target} onChange={e=>editItem(i.id,"target",e.target.value)}><option>ROMANEIO</option><option>ETIQUETA</option><option>AMBOS</option></select></td><td><select value={i.position} onChange={e=>editItem(i.id,"position",e.target.value)}><option value="CABECALHO">Cabeçalho</option><option value="ANTES_TABELA">Antes da tabela</option><option value="OBSERVACAO">Observação</option><option value="RODAPE">Rodapé</option></select></td><td><button className="btn ghost" onClick={()=>removeItem(i.id)}><Trash2 size={15}/></button></td></tr>)}</tbody></table></div>}</section>
 <div className="actions"><button className="btn ghost" onClick={reset}><RotateCcw size={16}/> Restaurar padrões</button><button className="btn primary" onClick={save}><Save size={16}/> {saved?"Salvo":"Salvar configurações"}</button></div>
 </main></div>
}
