"use client";
import { useState } from "react";
import Link from "next/link";
import { UploadCloud, FileText, Settings2, History, LogOut, CheckCircle2, Printer, Download, PackageCheck } from "lucide-react";
import type { ProcessingResult } from "@/lib/types";

export default function DashboardClient(){
 const [pedido,setPedido]=useState<File|null>(null),[usinagem,setUsinagem]=useState<File|null>(null),[result,setResult]=useState<ProcessingResult|null>(null),[loading,setLoading]=useState(false),[progress,setProgress]=useState(0),[error,setError]=useState("");
 async function processar(){if(!pedido)return;setLoading(true);setError("");setProgress(18);const fd=new FormData();fd.append("pedido",pedido);if(usinagem)fd.append("usinagem",usinagem);const t=setInterval(()=>setProgress(p=>Math.min(88,p+7)),230);try{const r=await fetch("/api/process",{method:"POST",body:fd});const j=await r.json();if(!r.ok)throw new Error(j.error||"Falha ao processar");setResult(j);setProgress(100)}catch(e:any){setError(e.message)}finally{clearInterval(t);setLoading(false)}}
 function editRow(pi:number,ri:number,key:string,value:string){if(!result)return;const copy=structuredClone(result);const row:any=copy.packages[pi].rows[ri];row[key]=["quantity","lengthMm","widthMm","thicknessMm","volume"].includes(key)?(value===""?undefined:Number(value)):value;setResult(copy)}
 async function download(kind:"romaneio"|"etiquetas"){if(!result)return;const r=await fetch(`/api/generate/${kind}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(result)});const b=await r.blob();const u=URL.createObjectURL(b);const a=document.createElement("a");a.href=u;a.download=kind==="romaneio"?`Romaneio ${result.orderNumber}.xlsx`:`Etiquetas ${result.orderNumber}.pdf`;a.click();URL.revokeObjectURL(u)}
 async function logout(){await fetch("/api/auth/logout",{method:"POST"});location.href="/login"}
 return <div className="shell"><header className="topbar"><div className="brand"><span className="leaf"/><div>famossul<small>Gerador de romaneios e etiquetas</small></div></div><button className="btn ghost" onClick={logout}><LogOut size={16}/> Sair</button></header><div className="layout"><aside className="sidebar"><div className="navitem active"><PackageCheck size={18}/> Novo romaneio</div><Link className="navitem" href="/history"><History size={18}/> Histórico</Link><div className="navitem"><Settings2 size={18}/> Configurações</div></aside><main className="main"><div className="eyebrow">Operação logística</div><h1 className="title">Gerar romaneio</h1><p className="subtitle">Envie o pedido e, quando houver, a planilha de usinagem. O sistema prepara os pallets para conferência antes da emissão.</p>
 {!result&&<div className="card uploadcard"><div className="uploadgrid"><label className={`drop ${pedido?"has":""}`}><UploadCloud size={28}/><strong>{pedido?pedido.name:"Pedido"}</strong><span>PDF do pedido emitido pelo sistema</span><input hidden type="file" accept=".pdf" onChange={e=>setPedido(e.target.files?.[0]||null)}/>{pedido&&<span style={{color:"var(--green)"}}>✓ arquivo carregado</span>}</label><label className={`drop ${usinagem?"has":""}`}><FileText size={28}/><strong>{usinagem?usinagem.name:"Usinagem (opcional)"}</strong><span>XLS ou XLSX quando o pedido possuir item usinado</span><input hidden type="file" accept=".xls,.xlsx" onChange={e=>setUsinagem(e.target.files?.[0]||null)}/>{usinagem&&<span style={{color:"var(--green)"}}>✓ arquivo carregado</span>}</label></div>{loading&&<div className="progress"><div className="bar"><div style={{width:`${progress}%`}}/></div><div className="steps">{progress<35?"Lendo pedido...":progress<58?"Identificando produtos e medidas...":progress<78?"Cruzando usinagem...":progress<96?"Montando pallets...":"Conferência pronta."}</div></div>}{error&&<p className="error">{error}</p>}<div className="actions"><button className="btn secondary" disabled={!pedido||loading} onClick={()=>{setPedido(null);setUsinagem(null)}}>Limpar</button><button className="btn primary" disabled={!pedido||loading} onClick={processar}>{loading?"Processando...":"Processar pedido"}</button></div></div>}
 {result&&<><div className="summary"><div className="card metric"><span>Pedido</span><strong>{result.orderNumber}</strong></div><div className="card metric"><span>Cliente</span><strong style={{fontSize:16}}>{result.client}</strong></div><div className="card metric"><span>Pallets</span><strong>{result.packages.length}</strong></div><div className="card metric"><span>Usinagem</span><strong style={{fontSize:17}}>{result.hasMachining?"Identificada":"Não enviada"}</strong></div></div>{result.handSplit&&<div className="card" style={{padding:16,marginBottom:16}}><span className="badge">Mão identificada</span> <strong style={{marginLeft:8}}>{result.handSplit.right} Direitas / {result.handSplit.left} Esquerdas</strong></div>}{result.warnings.map((w,i)=><div className="warning" key={i}>⚠ {w}</div>)}<div style={{display:"grid",gap:16,marginTop:18}}>{result.packages.map((pkg,pi)=><section className="card" key={pkg.number}><div className="pkghead"><div><span className="pkgtitle">Pacote {pkg.number}</span> <span className="badge">Pallet {pkg.number} de {result.packages.length}</span></div><div>{pkg.totalVolume!==undefined&&<strong>{pkg.totalVolume.toFixed(3).replace('.',',')} m³</strong>}</div></div><div className="tablewrap"><table className="table"><thead><tr><th>Qtd.</th><th>Compr.</th><th>Larg.</th><th>Esp.</th><th>Produto</th><th>Obs.</th></tr></thead><tbody>{pkg.rows.map((row,ri)=><tr key={ri}><td><input value={row.quantity??""} onChange={e=>editRow(pi,ri,"quantity",e.target.value)}/></td><td><input value={row.lengthMm??""} onChange={e=>editRow(pi,ri,"lengthMm",e.target.value)}/></td><td><input value={row.widthMm??""} onChange={e=>editRow(pi,ri,"widthMm",e.target.value)}/></td><td><input value={row.thicknessMm??""} onChange={e=>editRow(pi,ri,"thicknessMm",e.target.value)}/></td><td><input style={{minWidth:310}} value={row.product} onChange={e=>editRow(pi,ri,"product",e.target.value)}/></td><td><input value={row.observation??""} onChange={e=>editRow(pi,ri,"observation",e.target.value)}/></td></tr>)}</tbody></table></div></section>)}</div><div className="actions" style={{marginTop:24,position:"sticky",bottom:16}}><button className="btn ghost" onClick={()=>{setResult(null);setProgress(0)}}>Novo processamento</button><button className="btn secondary" onClick={()=>download("romaneio")}><Download size={16}/> Baixar romaneio</button><button className="btn primary" onClick={()=>download("etiquetas")}><Printer size={16}/> Gerar etiquetas</button></div></>}</main></div></div>
}
