"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { UploadCloud, FileText, Settings2, History, LogOut, Printer, Download, PackageCheck, Plus, Trash2, AlertTriangle, CheckCircle2, Info, RefreshCw } from "lucide-react";
import type { LogisticsConfig, MountType, ProcessingResult } from "@/lib/types";
import { DEFAULT_LOGISTICS_CONFIG, MOUNT_LABELS, sanitizeConfig } from "@/lib/settings";
import { rowVolume } from "@/lib/logistics";

const CONFIG_KEY="famossul-logistics-config-v1";
const mounts:MountType[]=["MONTADO_HS","MONTADO_TIMADEL","COMPLEMENTO_OBRA","REVENDA","MONTADO_ESTANCIA"];
const fmt=(n?:number)=>(n||0).toFixed(3).replace(".",",");

export default function DashboardClient(){
 const [pedido,setPedido]=useState<File|null>(null),[usinagem,setUsinagem]=useState<File|null>(null),[result,setResult]=useState<ProcessingResult|null>(null),[loading,setLoading]=useState(false),[progress,setProgress]=useState(0),[error,setError]=useState("");
 const [mountType,setMountType]=useState<MountType>("MONTADO_HS"); const [mixedOrder,setMixedOrder]=useState(false); const [config,setConfig]=useState<LogisticsConfig>(DEFAULT_LOGISTICS_CONFIG);
 useEffect(()=>{try{const raw=localStorage.getItem(CONFIG_KEY);if(raw)setConfig(sanitizeConfig(JSON.parse(raw)));}catch{}},[]);

 async function processar(){
  if(!pedido)return; setLoading(true);setError("");setProgress(12);
  const fd=new FormData();fd.append("pedido",pedido);if(usinagem)fd.append("usinagem",usinagem);fd.append("mountType",mountType);fd.append("mixedOrder",String(mixedOrder));fd.append("config",JSON.stringify(config));
  const t=setInterval(()=>setProgress(p=>Math.min(91,p+6)),260);
  try{const r=await fetch("/api/process",{method:"POST",body:fd});const j=await r.json();if(!r.ok)throw new Error(j.error||"Falha ao processar");setResult(j);setProgress(100)}catch(e:any){setError(e.message)}finally{clearInterval(t);setLoading(false)}
 }
 function recalc(copy:ProcessingResult,pi:number){const pkg=copy.packages[pi];if(!pkg)return;pkg.totalVolume=pkg.rows.reduce((s,r)=>s+rowVolume(r),0);const qty=pkg.rows.reduce((s,r)=>s+(r.quantity||0),0);if((pkg.limitM3&&pkg.totalVolume>pkg.limitM3+.0005)||(pkg.limitQuantity&&qty>pkg.limitQuantity))pkg.status="INVALIDO";else if(pkg.status==="INVALIDO")pkg.status="VALIDO";}
 function editRow(pi:number,ri:number,key:string,value:string){if(!result)return;const copy=structuredClone(result);const row:any=copy.packages[pi].rows[ri];row[key]=["quantity","games","lengthMm","widthMm","thicknessMm","volume"].includes(key)?(value===""?undefined:Number(value)):value;recalc(copy,pi);setResult(copy)}
 function addRow(pi:number){if(!result)return;const copy=structuredClone(result);copy.packages[pi].rows.push({quantity:1,product:"Novo produto",category:"OUTRO"});recalc(copy,pi);setResult(copy)}
 function removeRow(pi:number,ri:number){if(!result)return;const copy=structuredClone(result);copy.packages[pi].rows.splice(ri,1);recalc(copy,pi);setResult(copy)}
 function editOrderOption(key:string,value:string){if(!result)return;const copy=structuredClone(result);copy.orderOptions={...(copy.orderOptions||{mountType:copy.mountType}),[key]:value};setResult(copy)}
 function addPallet(){if(!result)return;const copy=structuredClone(result);copy.packages.push({number:copy.packages.length+1,rows:[],totalVolume:0,status:"ATENCAO",warnings:["Pallet criado manualmente para conferência."]});setResult(copy)}
 function moveRow(pi:number,ri:number,target:number){if(!result||target===pi)return;const copy=structuredClone(result);const [row]=copy.packages[pi].rows.splice(ri,1);copy.packages[target].rows.push(row);recalc(copy,pi);recalc(copy,target);setResult(copy)}
 async function download(kind:"romaneio"|"etiquetas"){if(!result)return;const invalid=result.packages.some(p=>p.status==="INVALIDO");if(invalid){setError("Existe pallet inválido. Corrija quantidade/cubagem antes de gerar os arquivos.");return;}const r=await fetch(`/api/generate/${kind}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(result)});if(!r.ok){setError(await r.text());return;}const b=await r.blob();const u=URL.createObjectURL(b);const a=document.createElement("a");a.href=u;a.download=kind==="romaneio"?`Romaneio ${result.orderNumber}.xlsx`:`Etiquetas ${result.orderNumber}.pdf`;a.click();URL.revokeObjectURL(u)}
 async function logout(){await fetch("/api/auth/logout",{method:"POST"});location.href="/login"}
 const totals=useMemo(()=>result?{m3:result.packages.reduce((s,p)=>s+(p.totalVolume||0),0),invalid:result.packages.filter(p=>p.status==="INVALIDO").length}:null,[result]);

 return <div className="shell"><header className="topbar"><div className="brand"><span className="leaf"/><div>famossul<small>Gerador de romaneios e etiquetas</small></div></div><button className="btn ghost" onClick={logout}><LogOut size={16}/> Sair</button></header><div className="layout"><aside className="sidebar"><div className="navitem active"><PackageCheck size={18}/> Novo romaneio</div><Link className="navitem" href="/history"><History size={18}/> Histórico</Link><Link className="navitem" href="/settings"><Settings2 size={18}/> Configurações</Link></aside><main className="main"><div className="eyebrow">Operação logística</div><h1 className="title">Gerar romaneio</h1><p className="subtitle">O sistema lê pedido + usinagem, aplica as regras da montagem escolhida, valida os pallets e só então libera romaneio e etiquetas.</p>
 {!result&&<div className="card uploadcard"><div className="mountBox"><label><strong>Tipo / local de montagem</strong><select value={mountType} onChange={e=>setMountType(e.target.value as MountType)}>{mounts.map(m=><option key={m} value={m}>{MOUNT_LABELS[m]}</option>)}</select></label><div><div className="rulePreview"><Info size={17}/><span>{MOUNT_LABELS[mountType]}: até <b>{config[mountType].maxDoors} portas</b>, <b>{fmt(config[mountType].maxM3)} m³</b>, alizar até <b>{config[mountType].maxTrimGames} jogos</b>.</span></div><label className="mixedToggle"><input type="checkbox" checked={mixedOrder} onChange={e=>setMixedOrder(e.target.checked)}/> Pedido misto (limite {fmt(config.mixedMaxM3)} m³/pallet)</label></div></div><div className="uploadgrid"><label className={`drop ${pedido?"has":""}`}><UploadCloud size={28}/><strong>{pedido?pedido.name:"Pedido"}</strong><span>PDF completo do pedido</span><input hidden type="file" accept=".pdf" onChange={e=>setPedido(e.target.files?.[0]||null)}/>{pedido&&<span style={{color:"var(--green)"}}>✓ arquivo carregado</span>}</label><label className={`drop ${usinagem?"has":""}`}><FileText size={28}/><strong>{usinagem?usinagem.name:"Usinagem (opcional)"}</strong><span>XLS/XLSX para mão, aplicação, medidas e ferragens</span><input hidden type="file" accept=".xls,.xlsx" onChange={e=>setUsinagem(e.target.files?.[0]||null)}/>{usinagem&&<span style={{color:"var(--green)"}}>✓ arquivo carregado</span>}</label></div>{loading&&<div className="progress"><div className="bar"><div style={{width:`${progress}%`}}/></div><div className="steps">{progress<28?"Lendo todas as páginas do pedido...":progress<48?"Normalizando produtos e medidas...":progress<67?"Cruzando usinagem, mão e aplicação...":progress<82?"Aplicando regras logísticas...":progress<96?"Validando cubagem e pallets...":"Conferência pronta."}</div></div>}{error&&<p className="error">{error}</p>}<div className="actions"><Link className="btn ghost" href="/settings"><Settings2 size={16}/> Regras</Link><button className="btn secondary" disabled={!pedido||loading} onClick={()=>{setPedido(null);setUsinagem(null)}}>Limpar</button><button className="btn primary" disabled={!pedido||loading} onClick={processar}>{loading?"Processando...":"Processar pedido"}</button></div></div>}
 {result&&<><div className="reviewHeader card"><div><div className="eyebrow">Revisão do pedido</div><h2 style={{margin:"5px 0"}}>Pedido {result.orderNumber}</h2><div className="muted">{result.client} • {result.destination||"Destino não identificado"}</div></div><div className="reviewMount"><span>Montagem</span><strong>{MOUNT_LABELS[result.mountType]}</strong>{result.mixedOrder&&<span className="badge warnBadge">PEDIDO MISTO</span>}</div></div>
 <div className="summary"><div className="card metric"><span>Pallets</span><strong>{result.packages.length}</strong></div><div className="card metric"><span>Total m³</span><strong>{fmt(totals?.m3)}</strong></div><div className="card metric"><span>Usinagem</span><strong style={{fontSize:17}}>{result.hasMachining?"Identificada":"Não enviada"}</strong></div><div className="card metric"><span>Validação</span><strong style={{fontSize:17,color:totals?.invalid?"var(--danger)":"var(--green2)"}}>{totals?.invalid?`${totals.invalid} inválido(s)`:"Tudo validado"}</strong></div></div>
 {result.warnings.map((w,i)=><div className="warning" key={i}><AlertTriangle size={15}/> {w}</div>)}
 <section className="card orderExtras"><div className="pkghead" style={{padding:0,border:0,background:"transparent"}}><div><strong>Dados adicionais do romaneio</strong><div className="muted">Opcionais. São impressos no modelo oficial quando preenchidos.</div></div></div><div className="extrasGrid"><label>Motorista<input value={result.orderOptions?.motorista||""} onChange={e=>editOrderOption("motorista",e.target.value)}/></label><label>Transportadora<input value={result.orderOptions?.transportadora||""} onChange={e=>editOrderOption("transportadora",e.target.value)}/></label><label>Placa<input value={result.orderOptions?.placa||""} onChange={e=>editOrderOption("placa",e.target.value)}/></label><label>Nota Fiscal<input value={result.orderOptions?.notaFiscal||""} onChange={e=>editOrderOption("notaFiscal",e.target.value)}/></label><label>Texto extra no romaneio<input value={result.orderOptions?.romaneioExtraText||""} onChange={e=>editOrderOption("romaneioExtraText",e.target.value)}/></label><label>Texto extra na etiqueta<input value={result.orderOptions?.etiquetaExtraText||""} onChange={e=>editOrderOption("etiquetaExtraText",e.target.value)}/></label></div></section>
 <div className="actions" style={{justifyContent:"space-between",marginBottom:12}}><button className="btn secondary" onClick={addPallet}><Plus size={15}/> Criar pallet</button><span className="muted">Edite qualquer linha; a cubagem é recalculada automaticamente.</span></div>
 <div style={{display:"grid",gap:16}}>{result.packages.map((pkg,pi)=><section className={`card palletCard ${pkg.status?.toLowerCase()||""}`} key={`${pkg.number}-${pi}`}><div className="pkghead"><div><span className="pkgtitle">Pallet {pkg.number}</span> <span className={`statusBadge ${pkg.status?.toLowerCase()}`}>{pkg.status==="VALIDO"?<CheckCircle2 size={13}/>:<AlertTriangle size={13}/>} {pkg.status||"CONFERIR"}</span>{pkg.ruleApplied&&<div className="ruleLine"><Info size={13}/>{pkg.ruleApplied}</div>}{pkg.warnings?.map((w,i)=><div className="specialRule" key={i}>{w}</div>)}</div><div className="volumeBlock"><strong>{fmt(pkg.totalVolume)} m³</strong>{pkg.limitM3&&<small>limite {fmt(pkg.limitM3)} m³</small>}</div></div><div className="tablewrap"><table className="table"><thead><tr><th>Jogos</th><th>Qtd.</th><th>Compr.</th><th>Larg.</th><th>Esp.</th><th>Produto completo</th><th>Obs./Mão</th><th>Mover</th><th></th></tr></thead><tbody>{pkg.rows.map((row,ri)=><tr key={ri}><td><input value={row.games??""} onChange={e=>editRow(pi,ri,"games",e.target.value)}/></td><td><input value={row.quantity??""} onChange={e=>editRow(pi,ri,"quantity",e.target.value)}/></td><td><input value={row.lengthMm??""} onChange={e=>editRow(pi,ri,"lengthMm",e.target.value)}/></td><td><input value={row.widthMm??""} onChange={e=>editRow(pi,ri,"widthMm",e.target.value)}/></td><td><input value={row.thicknessMm??""} onChange={e=>editRow(pi,ri,"thicknessMm",e.target.value)}/></td><td><textarea className="productEdit" value={row.product} onChange={e=>editRow(pi,ri,"product",e.target.value)}/></td><td><textarea className="obsEdit" value={row.observation??""} onChange={e=>editRow(pi,ri,"observation",e.target.value)}/></td><td><select value={pi} onChange={e=>moveRow(pi,ri,Number(e.target.value))}>{result.packages.map((p,idx)=><option key={idx} value={idx}>{idx===pi?"Atual":`Pallet ${p.number}`}</option>)}</select></td><td><button className="btn ghost" title="Excluir linha" onClick={()=>removeRow(pi,ri)}><Trash2 size={15}/></button></td></tr>)}</tbody></table></div><div className="palletFooter"><button className="btn secondary" onClick={()=>addRow(pi)}><Plus size={15}/> Adicionar item</button><button className="btn ghost" onClick={()=>{if(!result)return;const c=structuredClone(result);recalc(c,pi);setResult(c)}}><RefreshCw size={14}/> Recalcular</button></div></section>)}</div>
 <div className="actions stickyActions"><button className="btn ghost" onClick={()=>{setResult(null);setProgress(0);setError("")}}>Novo processamento</button><button className="btn secondary" disabled={Boolean(totals?.invalid)} onClick={()=>download("romaneio")}><Download size={16}/> Baixar romaneio</button><button className="btn primary" disabled={Boolean(totals?.invalid)} onClick={()=>download("etiquetas")}><Printer size={16}/> Gerar etiquetas</button></div>{error&&<p className="error">{error}</p>}</>}
 </main></div></div>
}
